name: flutter_html_editor
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^0.3.22+1
  mime: ^0.9.7

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - lib/summernote/summernote.html
    - lib/summernote/summernote-lite.min.css
    - lib/summernote/summernote-lite.min.js
    - lib/summernote/summernote-lite.min.js.map
    - lib/summernote/jquery-3.5.1.slim.min.js
    - lib/summernote/font/summernote.eot
    - lib/summernote/font/summernote.ttf
    - lib/summernote/font/summernote.woff
    - lib/summernote/font/summernote.woff2
    - lib/summernote/lang/summernote-zh-CN.min.js
    - lib/summernote/lang/summernote-fr-FR.min.js
  
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
